### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Xenoidian777** [Ubiquitouskiwi/BOOKWRMS#9]
**Describe the bug**
When entering used book barcode (not ISBN as expected to be the barcode) the server errors out. Should add error messages, and/or switch to searching for the book manually

**To Reproduce**
1. Go to 'add book’ 
2. Add a used books barcode 
3. If it is not a valid ISBN internal sever error appears 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Ubiquitouskiwi** [comment]
Added error message on add book page for when isbn is not valid.
